import Foundation

// Writes a Swift file that exposes the embedded lilypond tool path.
// Usage: lp-path-gen --tool-path /abs/path/to/lilypond --out <outputDir>

struct CLI {
    var toolPath: String = ""
    var outDir: URL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

    init(args: [String]) {
        var it = args.makeIterator()
        while let a = it.next() {
            switch a {
            case "--tool-path": toolPath = it.next() ?? ""
            case "--out": outDir = URL(fileURLWithPath: it.next() ?? ".")
            default: break
            }
        }
    }
}

let cli = CLI(args: Array(CommandLine.arguments.dropFirst()))
try FileManager.default.createDirectory(at: cli.outDir, withIntermediateDirectories: true)
let file = cli.outDir.appendingPathComponent("LilyPondEmbeddedPath.swift")
let sanitized = cli.toolPath.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
let contents = """
// Generated by LilyPondPathPlugin — do not edit.
public enum LilyPondEmbedded {
    public static let toolPath: String = "\(sanitized)"
}
"""
try contents.data(using: .utf8)!.write(to: file)
print("wrote \(file.path)")

